---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "test2" .Values.test2.name }}-deployment
  namespace: {{ default "dev" .Values.namespace }}
spec:
  replicas: {{ default "1" .Values.test2.replicas }}
  selector:
    matchLabels:
      app: {{ default "test2" .Values.test2.name }}
  strategy:
    type: {{ default "Recreate" .Values.test2.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ default "test2" .Values.test2.name }}
    spec:
      containers:
      - args:
        - "{{ .Values.test2.text }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        name: {{ default "test2" .Values.test2.name }}-app
        resources:
          limits:
            cpu: {{ default "200m" .Values.test2.resources.limits.cpu }}
            memory: {{ default "200Mi" .Values.test2.resources.limits.memory }}
          requests:
            cpu: {{ default "100m" .Values.test2.resources.requests.cpu }}
            memory: {{ default "100Mi" .Values.test2.resources.requests.memory }}
        ports:
        - containerPort: {{ default "5678" .Values.test2.port }}
      restartPolicy: {{ default "Always" .Values.test2.restartPolicy }}
