---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "test1" .Values.test1.name }}-deployment
  namespace: {{ default "dev" .Values.namespace }}
spec:
  replicas: {{ default "1" .Values.test1.replicas }}
  selector:
    matchLabels:
      app: {{ default "test1" .Values.test1.name }}
  strategy:
    type: {{ default "Recreate" .Values.test1.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ default "test1" .Values.test1.name }}
    spec:
      containers:
      - args:
        - "{{ .Values.test1.text }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        name: {{ default "test1" .Values.test1.name }}-app
        resources:
          limits:
            cpu: {{ default "200m" .Values.test1.resources.limits.cpu }}
            memory: {{ default "200Mi" .Values.test1.resources.limits.memory }}
          requests:
            cpu: {{ default "100m" .Values.test1.resources.requests.cpu }}
            memory: {{ default "100Mi" .Values.test1.resources.requests.memory }}
        ports:
        - containerPort: {{ default "5678" .Values.test1.port }}
      restartPolicy: {{ default "Always" .Values.test1.restartPolicy }}
