---
apiVersion: v1
kind: Service
metadata:
  name: {{ default "test1" .Values.test1.name }}
  namespace: {{ default "dev" .Values.namespace }}
spec:
  ports:
  - name: {{ default "test1" .Values.test1.name }}-{{ default "5678" .Values.test1.port }}
    port: {{ default "5678" .Values.test1.port }}
    targetPort: {{ default "5678" .Values.test1.port }}
  selector:
    name: {{ default "test1" .Values.test1.name }}